pipeline {
    agent any
    stages {
        stage('Setting up') {
            steps {
                echo "Checking out package from OBS"
                echo "Is osc password in cleartext? ${oscpw}"
                echo "Updating package source"
                echo "Submitting to staging project"
                echo "Waiting for package to build"
                echo "Setting up test nodes"
                echo "Setting up repositories"
            }
        }
        stage('Installing') {
        }
        stage('Testing') {
        }
        stage('Results') {
        }
    }
}
