pipeline {
    agent any
    stages {
        stage('Set up cloud nodes') {
        }
        stage('Check pull request') {
            agent {
                label 'cloud-testbuild-pr'
            }
            steps {
                sh "scripts/crowbar-testbuild.rb -o ${ghorg} -r ${ghrepo} -p ${pr_str} -c scripts/ardana-testbuild.yaml"
                /* scp to deployer node */
                /* run tests */
                echo "Tests passed!"
            }
        }
        stage('Run tests') {
            steps {
              waitUntil {
                sh "python3 jenkins/ci.suse.de/check-if-merged.py'
              }
              echo "The pull request merged!"
            }
        }
        stage('Submit to OBS') {
            steps {
                echo "Done"
            }
        }
    }
}
