---
- name: Setup repositories on the deployer node
  hosts: hosts
  gather_facts: False

  vars:
    clouddata_server: provo-clouddata.cloud.suse.de
    download_suse_server: download.suse.de
    cloudsource: SUSE-OpenStack-Cloud-8-devel-staging

  tasks:
  # SLES repos
  - name: Create srv directories
    file:
      state: directory
      path: /srv/tftpboot/suse-12.3/x86_64/repos/{{ item }}
    with_items:
      - Cloud
      - SLES12-SP3-Pool
      - SLES12-SP3-Updates
      - SUSE-OpenStack-Cloud-8-Pool
      - SUSE-OpenStack-Cloud-8-Updates

  - name: Mount zypper repos
    mount:
      state: mounted
      fstype: nfs
      opts: ro,nosuid,rsize=8192,wsize=8192,hard,intr,nolock
      name: /srv/tftpboot/suse-12.3/x86_64/repos/{{ item.name }}
      src: "{{ clouddata_server }}:/srv/nfs/repos/x86_64/{{ item.src }}"
    with_items:
      - name: Cloud
        src: "{{ cloudsource }}"
      - name: SLES12-SP3-Pool
        src: SLES12-SP3-Pool
      - name: SLES12-SP3-Updates
        src:  SLES12-SP3-Updates
      - name: SUSE-OpenStack-Cloud-8-Pool
        src: SUSE-OpenStack-Cloud-8-Pool
      - name: SUSE-OpenStack-Cloud-8-Updates
        src: SUSE-OpenStack-Cloud-8-Updates

  - name: Add zypper repos
    zypper_repository:
      repo: "/srv/tftpboot/suse-12.3/x86_64/repos/{{ item }}"
      name: "{{ item }}"
    with_items:
      - Cloud
      - SLES12-SP3-Pool
      - SLES12-SP3-Updates
      - SUSE-OpenStack-Cloud-8-Pool
      - SUSE-OpenStack-Cloud-8-Updates

  - name: Repo for sshpass
    zypper_repository:
      repo: "http://download.suse.de/ibs/QA:/SLE12SP3/update/"
      name: sshpass

  # Refresh all repos
  - name: Refresh zypper repositories
    zypper_repository:
      repo: '*'
      auto_import_keys: yes
      runrefresh: yes

  - name: Install sshpass
    zypper:
      name: 'sshpass'
      state: present

  - name: Remove Repo for sshpass
    zypper_repository:
      repo: "http://download.suse.de/ibs/QA:/SLE12SP3/update/"
      name: sshpass
      state: absent

  # NOTE: ansible's zypper extra_args are only supported in >= 2.4 and even if that version,
  # adding --replacefiles does not work
  # FIXME: Resolve the file conflicts in the ardana packages and use the zypper module
  - name: Install ardana pattern
    command: zypper -n in patterns-cloud-ardana
